all:
	gcc -o createthread createthread.c -lpthread
	gcc -o oncerun oncerun.c -lpthread
	gcc -o jointhread jointhread.c -lpthread
	gcc -o tsd tsd.c -lpthread
	gcc -o pthread_mutex pthread_mutex.c -lpthread
	gcc -o condition condition.c -lpthread


clean:
	rm -rf createthread oncerun jointhread tsd pthread_mutex condition

